import React, { useEffect } from 'react'
import { Link } from 'react-router-dom'
import Header from '../../features/landing/components/Header'
import Footer from '../../features/landing/components/Footer'

const TermsOfService = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="relative flex min-h-screen w-full flex-col bg-white">
      <Header />

      {/* Main Content */}
      <main className="flex-1 bg-gray-50 pt-20">
        <div className="max-w-4xl mx-auto px-6 py-12">
          <div className="text-center mb-12 pb-8 border-b-2 border-gray-200">
            <h1 className="text-4xl font-black text-[#1A2B48] mb-2">Terms and Conditions</h1>
            <p className="text-lg text-gray-500 font-medium">Automated Live Information for Seismic Tracking and Observation (ALISTO)</p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">GENERAL</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              The Terms and Conditions contained herein on this web and mobile application (the "App") shall govern your use of this App, including all pages to which you may be redirected. These terms apply in full force and effect to your use of this App. Your personal data, whenever provided within the App (including geolocation data for alert purposes) shall be processed and shall be governed by the provisions of the Republic Act (RA) No 10173 or the Data Privacy Act of 2012 (DPA), and all other applicable laws. Whenever used herein, "App Owner" shall mean the Researchers and Developers responsible for the creation and maintenance of the ALISTO application.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">AUTHORITY</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              By registering in the App, you warrant that you are duly authorized to register, request access, and supply information on your behalf. The App Owner may, at its sole discretion, request additional or supporting documents to prove such authority. You also warrant that all information supplied is verified, true, and correct to the best of your knowledge.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">USE</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              Through registration and by having access to the App, you hereby warrant that the App shall only be used for the following purposes:
            </p>
            <ul className="space-y-3 mb-4">
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Accessing real-time seismic data and interactive visualizations sourced from official government agencies, such as DOST-PHIVOLCS.
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Receiving personalized alert notifications based on seismic or volcanic activity near your registered or current geolocation.
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Obtaining risk level assessments and predictions generated by the App's machine learning models for disaster preparedness.
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Utilizing the AI-powered chatbot for informational support on seismic updates, risk levels, and preparedness guidelines.
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Any other public safety and disaster preparedness information services related to seismic and volcanic monitoring offered by the App Owner.
              </li>
            </ul>
          </div>

          <div className="bg-orange-50 border-l-4 border-primary p-6 rounded-lg mb-10">
            <h3 className="text-lg font-bold text-[#C85A2D] mb-3">Disclaimer on Risk & Predictive Data</h3>
            <p className="text-[#1A2B48] mb-4">
              You understand and acknowledge that the App's risk level predictions and real-time alerts are based on data from official sources (e.g., DOST-PHIVOLCS), historical records, and machine learning models. These models provide estimations and analyses, not guaranteed forecasts. Earthquakes and volcanic eruptions are complex, unpredictable natural phenomena.
            </p>
            <p className="text-[#1A2B48] mb-4">
              The App Owner (Researchers/Developers), their affiliates, and partners are not liable for any direct, indirect, or consequential damages, including loss of life or property, arising from the accuracy, completeness, or timeliness of the information, alerts, or risk predictions provided by ALISTO.
            </p>
            <p className="text-[#1A2B48]">
              The App is a supplemental tool for awareness and preparedness and must not replace official warnings, advisories, or mandatory evacuation orders issued by DOST-PHIVOLCS, NDMMC, or local government units (LGUs).
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">RESTRICTIONS</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              You are expressly and emphatically restricted from all of the following:
            </p>
            <ul className="space-y-3 mb-4">
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Selling, sub-licensing, and/or otherwise commercializing the App or its data;
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Misrepresenting, modifying, or republishing the seismic data or risk assessments provided by the App as official government warnings or advisories;
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Using the App or any of the information in illegal or unlawful activities;
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Publicly performing and/or showing any App material without proper attribution to ALISTO and the official data sources (e.g., DOST-PHIVOLCS);
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Using this App in any way that is, or may be, damaging to this App (e.g., attempting to disrupt the real-time data feed);
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Engaging in any data mining, data harvesting, data extracting, or any other similar activity in relation to this App, or while using this App, for commercial purposes;
              </li>
              <li className="relative pl-6 text-[#1A2B48] leading-7">
                <span className="absolute left-0 text-[#C85A2D] font-bold text-xl">•</span>
                Using the App or its data for any activity that may cause panic or public disorder.
              </li>
            </ul>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">PROFILE & DATA PRIVACY</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              All information gathered by the App, particularly your geolocation data and any data provided for personalized alerts, shall be treated as confidential. This App uses personal information to the extent strictly necessary to provide location-specific alerts and to comply with the DPA.
            </p>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              By enabling location services or providing your address, you explicitly consent to the App using this information to deliver personalized alerts and risk information relevant to your location. This data will be handled in accordance with the App Owner's Data Privacy Policy.
            </p>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              When required by the App Owner's Privacy Policy and the laws, and before the App uses or processes your data for any other purpose, the App Owner will secure your consent. The App Owner shall use the information provided by the User in accordance with the processes in Sections 12 and 13 of the Data Privacy Act of 2012.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">LIMITATION OF LIABILITY</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              In no event shall the App Owner nor any of its officers, directors, and employees, be liable to you for breaches arising out of or in any way connected with your use of this App, whenever such use is contrary to these terms and conditions. The App Owner, including its officers, directors, and employees shall not be liable for any indirect, consequential or special liability arising out of or in any way related to your use of this App, not in accordance to these terms.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-[#C85A2D] mb-4 uppercase tracking-wide">UPDATE IN TERMS</h2>
            <p className="text-[#1A2B48] leading-7 mb-4 text-justify">
              The App Owner is permitted to revise these Terms at any time as it sees fit. By using this App, you are expected to review such Terms on a regular basis to ensure you understand all terms and conditions governing the use of this App.
            </p>
          </div>

          <div className="text-center">
            <Link 
              to="/" 
              className="inline-flex items-center gap-2 bg-primary hover:bg-[#d86f0f] text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg"
            >
              <span className="text-xl">←</span>
              Back to Home
            </Link>
          </div>

          <div className="text-center text-gray-500 text-sm italic mt-12 pt-8 border-t border-gray-300">
            Last Updated: October 2025
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default TermsOfService